[package]

name = "gtfs-map"
version = "0.0.1"
authors = ["George Schneeloch <bostonbusmap@gmail.com>"]
edition = "2021"

[dependencies]
gtfs-map-lib = { path = "gtfs-map-lib" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process", "fs"] }
getopts = "*"
